-- Rate-limit ledger for edge functions. A single RPC atomically records an
-- attempt and returns whether the caller is currently over quota for the
-- given bucket. Zero dependencies outside Postgres — simpler than Redis for
-- our scale and avoids a new service.

CREATE TABLE IF NOT EXISTS public.rate_limit_hits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  bucket text NOT NULL,
  hit_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rate_limit_hits_lookup
  ON public.rate_limit_hits (user_id, bucket, hit_at DESC);

ALTER TABLE public.rate_limit_hits ENABLE ROW LEVEL SECURITY;
-- service_role only writes; no public policies.

-- Record a hit and return whether the caller is throttled. A hit *is*
-- recorded even when throttled — a client hammering us will see continuous
-- 429s rather than slipping through after the window rolls.
CREATE OR REPLACE FUNCTION public.rate_limit_check(
  p_user_id uuid,
  p_bucket text,
  p_max_hits integer,
  p_window_seconds integer
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _hits integer;
  _earliest timestamptz;
  _retry_after integer;
BEGIN
  INSERT INTO public.rate_limit_hits (user_id, bucket) VALUES (p_user_id, p_bucket);

  SELECT count(*), min(hit_at)
  INTO _hits, _earliest
  FROM public.rate_limit_hits
  WHERE user_id = p_user_id
    AND bucket = p_bucket
    AND hit_at > now() - (p_window_seconds || ' seconds')::interval;

  IF _hits > p_max_hits THEN
    _retry_after := greatest(
      1,
      p_window_seconds - extract(epoch FROM (now() - _earliest))::integer
    );
    RETURN jsonb_build_object(
      'throttled', true,
      'retry_after', _retry_after,
      'hits', _hits
    );
  END IF;

  RETURN jsonb_build_object('throttled', false, 'hits', _hits);
END;
$$;

-- Service-role only. Exposing this to authenticated users would let them
-- enumerate other users' request patterns via the p_user_id arg.
REVOKE EXECUTE ON FUNCTION public.rate_limit_check(uuid, text, integer, integer)
  FROM PUBLIC, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.rate_limit_check(uuid, text, integer, integer) TO service_role;

-- Cleanup helper: prune hits older than 1 hour. Keeps the table small.
-- Trigger from a scheduled job (supabase/cron) or manually.
CREATE OR REPLACE FUNCTION public.cleanup_rate_limit_hits()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _deleted integer;
BEGIN
  DELETE FROM public.rate_limit_hits WHERE hit_at < now() - interval '1 hour';
  GET DIAGNOSTICS _deleted = ROW_COUNT;
  RETURN _deleted;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.cleanup_rate_limit_hits()
  FROM PUBLIC, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.cleanup_rate_limit_hits() TO service_role;
